/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Analysis */
        get: operations["read_analysis_api_v1_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}/suggestions/{suggestion_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Suggestion */
        post: operations["review_suggestion_api_v1_analyses__analysis_id__suggestions__suggestion_id__reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Note */
        post: operations["create_note_api_v1_notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Note */
        get: operations["read_note_api_v1_notes__note_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/{note_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Note */
        post: operations["analyze_note_api_v1_notes__note_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/{note_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Note History
         * @description One note version: its analyses and their reviews. A revised note is a new note, so
         *     reviews of an earlier version never carry forward (DESIGN.md §4.2).
         */
        get: operations["note_history_api_v1_notes__note_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisResult */
        AnalysisResult: {
            /** Analysis Id */
            analysis_id: string;
            code_sets: components["schemas"]["CodeSetSelection"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            em: components["schemas"]["EmResult"] | null;
            error: components["schemas"]["PipelineError"] | null;
            /** Facts */
            facts: components["schemas"]["ClinicalFact"][];
            /** Gaps */
            gaps: components["schemas"]["Gap"][];
            /** Latency Ms */
            latency_ms: number;
            /** Model */
            model: string;
            /** Model Errors */
            model_errors: number;
            /** Note Id */
            note_id: string;
            /** Prompt Version */
            prompt_version: string;
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "failed";
            /** Suggestions */
            suggestions: components["schemas"]["Suggestion"][];
        };
        /** ClinicalFact */
        ClinicalFact: {
            /** Concept */
            concept: string;
            /** Details */
            details: {
                [key: string]: string;
            };
            /** Evidence */
            evidence: number[];
            /** Fact Id */
            fact_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "condition" | "procedure" | "medication";
            /** Links */
            links: components["schemas"]["FactLink"][];
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "history" | "ruled_out" | "denied" | "suspected" | "performed" | "planned";
        };
        /** CodeSetSelection */
        CodeSetSelection: {
            /** Cpt */
            cpt: string | null;
            /** Icd10Cm */
            icd10cm: string;
        };
        /** EmResult */
        EmResult: {
            /** Code */
            code: string | null;
            /** Mdm Level */
            mdm_level: ("straightforward" | "low" | "moderate" | "high") | null;
            /** Missing */
            missing: string[];
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Analysis Id */
            analysis_id?: string | null;
            /** Error Code */
            error_code: string;
            /** Message */
            message: string;
        };
        /** FactLink */
        FactLink: {
            /** Target Fact Id */
            target_fact_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "caused_by" | "associated_with";
        };
        /** Gap */
        Gap: {
            /** Affects Codes */
            affects_codes: string[];
            /** Gap Id */
            gap_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "missing" | "ambiguous" | "conflicting" | "unsupported";
            /** Missing */
            missing: string;
            /** Query Text */
            query_text: string;
            /** Rule Id */
            rule_id: string | null;
            /**
             * Severity
             * @enum {string}
             */
            severity: "blocking" | "review" | "info";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Code Sets */
            code_sets: string[];
            /** Db */
            db: boolean;
            /**
             * Service
             * @constant
             */
            service: "codecare-api";
        };
        /** Note */
        Note: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Parent Note Id */
            parent_note_id: string | null;
            /**
             * Patient Type
             * @enum {string}
             */
            patient_type: "new" | "established";
            /** Sentences */
            sentences: components["schemas"]["Sentence"][];
            /** Text */
            text: string;
            /**
             * Visit Date
             * Format: date
             */
            visit_date: string;
        };
        /** NoteCreate */
        NoteCreate: {
            /** Parent Note Id */
            parent_note_id?: string | null;
            /**
             * Patient Type
             * @enum {string}
             */
            patient_type: "new" | "established";
            /** Text */
            text: string;
            /**
             * Visit Date
             * Format: date
             */
            visit_date: string;
        };
        /**
         * NoteHistory
         * @description One note version with its analyses and their reviews (GET /notes/{id}/history).
         */
        NoteHistory: {
            /** Analyses */
            analyses: components["schemas"]["AnalysisResult"][];
            /** Later Versions */
            later_versions: string[];
            note: components["schemas"]["Note"];
            /** Previous Versions */
            previous_versions: string[];
            /** Reviews */
            reviews: components["schemas"]["ReviewEvent"][];
        };
        /** PipelineError */
        PipelineError: {
            /**
             * Code
             * @enum {string}
             */
            code: "LLM_UNAVAILABLE" | "LLM_BAD_OUTPUT" | "TIMEOUT" | "CODE_SET_MISSING" | "DB_ERROR" | "PIPELINE_ERROR";
            /** Message */
            message: string;
            /** Stage */
            stage: string;
        };
        /**
         * ReviewEvent
         * @description One stored review. Reviews are append-only: never updated or deleted.
         */
        ReviewEvent: {
            /**
             * Action
             * @enum {string}
             */
            action: "accept" | "edit" | "reject";
            /** Analysis Id */
            analysis_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Reason */
            reason: string | null;
            /** Replacement Code */
            replacement_code: string | null;
            /** Suggestion Id */
            suggestion_id: string;
        };
        /**
         * ReviewRequest
         * @description A coder's decision on one suggestion. Checked here so a bad body is 422 VALIDATION_ERROR.
         */
        ReviewRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "accept" | "edit" | "reject";
            /** Reason */
            reason?: string | null;
            /** Replacement Code */
            replacement_code?: string | null;
        };
        /** RuleResult */
        RuleResult: {
            /** Affects Codes */
            affects_codes: string[];
            /** Message */
            message: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "pass" | "fail" | "needs_review";
            /** Rule Id */
            rule_id: string;
            /** Source Ref */
            source_ref: string;
        };
        /** Sentence */
        Sentence: {
            /** End */
            end: number;
            /** N */
            n: number;
            /** Section */
            section: string;
            /** Start */
            start: number;
            /** Text */
            text: string;
        };
        /** Suggestion */
        Suggestion: {
            /** Added By Rule */
            added_by_rule?: string | null;
            /** Code */
            code: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "strong" | "review" | "not_suggested";
            /** Description */
            description: string;
            /** Evidence */
            evidence: number[];
            /** Fact Ids */
            fact_ids: string[];
            /** Gap Ids */
            gap_ids: string[];
            /** Rule Results */
            rule_results: components["schemas"]["RuleResult"][];
            /** Suggestion Id */
            suggestion_id: string;
            /**
             * System
             * @enum {string}
             */
            system: "ICD-10-CM" | "CPT";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_analysis_api_v1_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_suggestion_api_v1_analyses__analysis_id__suggestions__suggestion_id__reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
                suggestion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewEvent"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_note_api_v1_notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_note_api_v1_notes__note_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_note_api_v1_notes__note_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    note_history_api_v1_notes__note_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteHistory"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
